apiVersion: v1
kind: Deployment
metadata:
  name: spark-worker-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spark-worker-1
  template:
    metadata:
      labels:
        app: spark-worker-1
    spec:
      containers:
        - name: spark-worker-1
          image: spark-worker-1-image:latest
          ports:
            - containerPort: 7077
